version: '3.3'
volumes:
   wp_db_vol
services:
   wpdbmysql:
     image: mysql:5.7
     volumes:
       - wp_db_vol:/var/lib/mysql
       - ./sqlimport:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - wpdbmysql
     image: wordpress:latest
     volumes:
       - ./wordpress:/var/www/html
     ports:
       - "${HOST_PORT}:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wpdbmysql:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

   phpmyadmin:
       image: phpmyadmin/phpmyadmin
       links:
         - wpdbmysql:mysql
       environment:
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         PMA_HOST: mysql
       ports:
        - "${PHP_MY_ADMIN_PORT}:80"
